language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: required
      dist: xenial

script: true

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags

notifications:
  email:
    on_success: never
